Trabalho Data Science - Análise Exploratória do Dataset de Receitas da Prefeitura Municipal de Curitiba

Alunos: Igor Cristian Gomes Mucharski - Raphael Marangoni - Vinicius Lisboa

--------------------------------------------------------------------------------

Vamos iniciar importando as Bibliotecas e clonando o repositório do Github com os datasets

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

sns.set()

%matplotlib inline

ModuleNotFoundError: No module named 'pandas'

In [ ]:
!git clone https://github.com/up-uppers/data-science-trabalho.git

Cloning into 'data-science-trabalho'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 33 (delta 7), reused 14 (delta 4), pack-reused 0
Unpacking objects: 100% (33/33), done.

Agora, vamos ler os dados do dataset limpo

In [ ]:
dataset = pd.read_csv('data-science-trabalho/dataset limpo/dataset_limpo.csv', on_bad_lines='skip', delimiter=';')

dataset

,CD_RECEITA,CD_CATEGORIA,DESCRICAO_CATEGORIA,CD_ORIGEM,DESCRICAO_ORIGEM,CD_ESPECIE,DESCRICAO_ESPECIE,CD_RUBRICA,DESCRICAO_RUBRICA,CD_ALINEA,DESCRICAO_ALINEA,CD_SUBALINEA,DESCRICAO_SUBALINEA,CD_EXERCICIO,DT_APROPRIACAO,TP_RECEITA_ORC,CD_EMPRESA,NM_EMPRESA,VL_RECEITA,"DS_FONTE,,,"
0,6000030700000000000000,6,RECEITA EXTRA-ORÇAMENTÁRIA,0,NaN,0,NaN,0.0,NaN,3.0,NaN,7.0,NaN,2022,2022-08-31,Extra-Orçamentária,9,Fundo de Urbanização de Curitiba,"61852,58","Retenções em Carater Consignatório,,"
1,1121040101000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",2,TAXAS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-09-23,Orçamentária,1,Prefeitura Municipal de Curitiba,"226,07","Taxas - Exercício Poder de Polícia,"
2,1121040101000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",2,TAXAS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-09-23,Orçamentária,1,Prefeitura Municipal de Curitiba,"270,03","Taxas - Exercício Poder de Polícia,"
3,1121040101000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",2,TAXAS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-09-23,Orçamentária,1,Prefeitura Municipal de Curitiba,"37,68","Taxas - Exercício Poder de Polícia,"
4,1121040101000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",2,TAXAS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-09-23,Orçamentária,1,Prefeitura Municipal de Curitiba,"2143,55","Taxas - Exercício Poder de Polícia,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90074,1112500402000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",1,IMPOSTOS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-08-18,Orçamentária,1,Prefeitura Municipal de Curitiba,"143,75","Demais Impostos Vinculados à Educação Básica,"
90075,1112500402000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",1,IMPOSTOS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-08-18,Orçamentária,1,Prefeitura Municipal de Curitiba,"345,01","Recursos Ordinários (Livres),"
90076,1112500402000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",1,IMPOSTOS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-08-18,Orçamentária,1,Prefeitura Municipal de Curitiba,"251,38","Saúde - Receitas Vinculadas (EC 29/00 - 15%),"
90077,1112500402000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",1,IMPOSTOS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-08-18,Orçamentária,1,Prefeitura Municipal de Curitiba,"418,97","Demais Impostos Vinculados à Educação Básica,"
90078,1112500402000000000000,1,Receitas Correntes,1,"Impostos,Taxas e Contribuições de Melhoria",1,IMPOSTOS,NaN,NaN,NaN,NaN,NaN,NaN,2022,2022-08-18,Orçamentária,1,Prefeitura Municipal de Curitiba,"1005,55","Recursos Ordinários (Livres),"

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90079 entries, 0 to 90078
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CD_RECEITA           90079 non-null  object
 1   CD_CATEGORIA         90079 non-null  int64
 2   DESCRICAO_CATEGORIA  90079 non-null  object
 3   CD_ORIGEM            90079 non-null  int64
 4   DESCRICAO_ORIGEM     80432 non-null  object
 5   CD_ESPECIE           90079 non-null  int64
 6   DESCRICAO_ESPECIE    80429 non-null  object
 7   CD_RUBRICA           8545 non-null   float64
 8   DESCRICAO_RUBRICA    0 non-null      float64
 9   CD_ALINEA            8545 non-null   float64
 10  DESCRICAO_ALINEA     0 non-null      float64
 11  CD_SUBALINEA         8545 non-null   float64
 12  DESCRICAO_SUBALINEA  0 non-null      float64
 13  CD_EXERCICIO         90079 non-null  int64
 14  DT_APROPRIACAO       90079 non-null  object
 15  TP_RECEITA_ORC       90079 non-null  object
 16  CD_EMPRESA           90079 non-null  int64
 17  NM_EMPRESA           90079 non-null  object
 18  VL_RECEITA           90079 non-null  object
 19  DS_FONTE,,,          90079 non-null  object
dtypes: float64(6), int64(5), object(9)
memory usage: 13.7+ MB